# name of your github action
name: CI

on:
  push:
    branches:
      - master

# this is where the magic happens, each job happens in parallel btw
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: master
      - uses: actions/setup-node@master
        with:
          node-version: 10.16
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Install dependencies
        run: yarn install
      - name: Build App
        run: yarn build-electron
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: Snippets Bar-${{ steps.package-version.outputs.current-version}}.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
