name: CI

on:
  push:
    branches:
      - master

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: master
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: set environment variables
        uses: allenevans/set-env@v1.0.0
        with:
          VERSION: ${{ steps.package-version.outputs.current-version}}
      - name: Printenv
        run: |
          echo "VERSION=${VERSION}"
          printenv

  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: master
      - uses: actions/setup-node@master
        with:
          node-version: 10.16
      - name: Install dependencies
        run: yarn install
      - name: build app
        run: yarn build-electron
      - name: package
        run: yarn package

  upload:
    needs: [build, version]
    runs-on: ubuntu-latest
    steps:
      - name: Check artifacts
        run: ls dist
      # - name: Upload to release
      #   uses: JasonEtco/upload-to-release@master
      #   with:
      #     args: dist/SnippetsBar-${VERSION}.dmg
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
