name: CI

on:
  push:
    branches:
      - master

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.step1.outputs.version }}
    steps:
      - uses: actions/checkout@master
        with:
          ref: master
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - id: step1
        run: echo "::set-output name=version::${{ steps.package-version.outputs.current-version}}"

  build:
    needs: [version]
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: master
      - uses: actions/setup-node@master
        with:
          node-version: 10.16
      - name: Install dependencies
        run: yarn install
      - name: build app
        run: yarn build-electron
      - name: package
        run: yarn package
      - name: upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: SnippetsBar-${{needs.version.outputs.version}}.dmg
          path: dist/SnippetsBar-${{needs.version.outputs.version}}.dmg

  upload:
    needs: [version, build]
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
